-- DB Example
-- version 0.0.1
--
-- Creation Time: May 06, 2017
-- MySQL Server version: 5.5.35-1
-- PHP Version: 5.5.9-

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `readability-study`
--

USE `readability-study`;

-- -------------------------------------------------------------------
-- Data

--
-- Data for table `Competency`
--

INSERT INTO `Competency` (`id`, `score`) VALUES
(1, 90),
(2, 25),
(3, 90),
(4, 90);

--
-- Data for table `User`
--

INSERT INTO `User` (`id`, `competency_id`) VALUES
('allowed', 1),
('notallowed', 2),
('rate', 3),
('forced_choice', 4);

--
-- Data for table `Tag`
--

INSERT INTO `Tag` (`value`) VALUES
('Length'),
('Width'),
('Variables'),
('Indentation'),
('ConditionalStatements'),
('Numbers'),
('Comments'),
('Methods'),
('Parameters'),
('ArrayLength'),
('Spaces'),
('Parentheses'),
('ArithmeticOperators'),
('Comparisons'),
('Assertions'),
('Classes'),
('Characters'),
('Strings'),
('Exceptions'),
('Nulls'),
('Casts'),
('Booleans'),
('Arrays'),
('Fields');

--
-- Data for table `Snippet`
--

INSERT INTO `Snippet` (`path`) VALUES
('public/snippets/arrays.TotalArraysFeature0_1.txt'),
('public/snippets/arrays.TotalArraysFeature0_2.txt'),
('public/snippets/arrays.TotalArraysFeature1_1.txt'),
('public/snippets/arrays.TotalArraysFeature1_2.txt'),
('public/snippets/arrays.TotalArraysFeature2_1.txt'),
('public/snippets/arrays.TotalArraysFeature2_2.txt'),
('public/snippets/assertions.HasAssertionsFeature0_1.txt'),
('public/snippets/assertions.HasAssertionsFeature0_2.txt'),
('public/snippets/assertions.HasAssertionsFeature1_1.txt'),
('public/snippets/assertions.HasAssertionsFeature1_2.txt'),
('public/snippets/assertions.HasAssertionsFeature2_1.txt'),
('public/snippets/assertions.HasAssertionsFeature2_2.txt'),
('public/snippets/assertions.TotalAssertionsFeature0_1.txt'),
('public/snippets/assertions.TotalAssertionsFeature0_2.txt'),
('public/snippets/assertions.TotalAssertionsFeature1_1.txt'),
('public/snippets/assertions.TotalAssertionsFeature1_2.txt'),
('public/snippets/assertions.TotalAssertionsFeature2_1.txt'),
('public/snippets/assertions.TotalAssertionsFeature2_2.txt'),
('public/snippets/assignments.MaxAssignmentsFeature0_1.txt'),
('public/snippets/assignments.MaxAssignmentsFeature0_2.txt'),
('public/snippets/assignments.MaxAssignmentsFeature1_1.txt'),
('public/snippets/assignments.MaxAssignmentsFeature1_2.txt'),
('public/snippets/characters.AverageComparisonOperatorsFeature0_1.txt'),
('public/snippets/characters.AverageComparisonOperatorsFeature0_2.txt'),
('public/snippets/characters.AverageComparisonOperatorsFeature1_1.txt'),
('public/snippets/characters.AverageComparisonOperatorsFeature1_2.txt'),
('public/snippets/characters.AverageComparisonOperatorsFeature2_1.txt'),
('public/snippets/characters.AverageComparisonOperatorsFeature2_2.txt'),
('public/snippets/characters.AverageParenthesesFeature0_1.txt'),
('public/snippets/characters.AverageParenthesesFeature0_2.txt'),
('public/snippets/characters.AverageParenthesesFeature1_1.txt'),
('public/snippets/characters.AverageParenthesesFeature1_2.txt'),
('public/snippets/characters.AverageParenthesesFeature2_1.txt'),
('public/snippets/characters.AverageParenthesesFeature2_2.txt'),
('public/snippets/characters.AveragePeriodsFeature0_1.txt'),
('public/snippets/characters.AveragePeriodsFeature0_2.txt'),
('public/snippets/characters.AveragePeriodsFeature1_1.txt'),
('public/snippets/characters.AveragePeriodsFeature1_2.txt'),
('public/snippets/characters.AveragePeriodsFeature2_1.txt'),
('public/snippets/characters.AveragePeriodsFeature2_2.txt'),
('public/snippets/characters.MaxIdOccurenceLineFeature0_1.txt'),
('public/snippets/characters.MaxIdOccurenceLineFeature0_2.txt'),
('public/snippets/characters.MaxIdOccurenceLineFeature1_1.txt'),
('public/snippets/characters.MaxIdOccurenceLineFeature1_2.txt'),
('public/snippets/characters.MaxOccurenceOfAnyCharInTestFeature0_1.txt'),
('public/snippets/characters.MaxOccurenceOfAnyCharInTestFeature0_2.txt'),
('public/snippets/characters.MaxOccurenceOfAnyCharInTestFeature1_1.txt'),
('public/snippets/characters.MaxOccurenceOfAnyCharInTestFeature1_2.txt'),
('public/snippets/characters.MaxOccurenceOfAnyCharInTestFeature2_1.txt'),
('public/snippets/characters.MaxOccurenceOfAnyCharInTestFeature2_2.txt'),
('public/snippets/characters.MaxTokensFeature0_1.txt'),
('public/snippets/characters.MaxTokensFeature0_2.txt'),
('public/snippets/characters.MaxTokensFeature1_1.txt'),
('public/snippets/characters.MaxTokensFeature1_2.txt'),
('public/snippets/characters.MaxTokensFeature2_1.txt'),
('public/snippets/characters.MaxTokensFeature2_2.txt'),
('public/snippets/characters.TotalArithmeticOperatorsFeature0_1.txt'),
('public/snippets/characters.TotalArithmeticOperatorsFeature0_2.txt'),
('public/snippets/characters.TotalArithmeticOperatorsFeature1_1.txt'),
('public/snippets/characters.TotalArithmeticOperatorsFeature1_2.txt'),
('public/snippets/characters.TotalArithmeticOperatorsFeature2_1.txt'),
('public/snippets/characters.TotalArithmeticOperatorsFeature2_2.txt'),
('public/snippets/characters.TotalComparisonOperatorsFeature0_1.txt'),
('public/snippets/characters.TotalComparisonOperatorsFeature0_2.txt'),
('public/snippets/characters.TotalComparisonOperatorsFeature1_1.txt'),
('public/snippets/characters.TotalComparisonOperatorsFeature1_2.txt'),
('public/snippets/characters.TotalComparisonOperatorsFeature2_1.txt'),
('public/snippets/characters.TotalComparisonOperatorsFeature2_2.txt'),
('public/snippets/characters.TotalParenthesesFeature0_1.txt'),
('public/snippets/characters.TotalParenthesesFeature0_2.txt'),
('public/snippets/characters.TotalParenthesesFeature1_1.txt'),
('public/snippets/characters.TotalParenthesesFeature1_2.txt'),
('public/snippets/characters.TotalParenthesesFeature2_1.txt'),
('public/snippets/characters.TotalParenthesesFeature2_2.txt'),
('public/snippets/characters.TotalTokensFeature0_1.txt'),
('public/snippets/characters.TotalTokensFeature0_2.txt'),
('public/snippets/characters.TotalTokensFeature1_1.txt'),
('public/snippets/characters.TotalTokensFeature1_2.txt'),
('public/snippets/characters.TotalTokensFeature2_1.txt'),
('public/snippets/characters.TotalTokensFeature2_2.txt'),
('public/snippets/comments.AverageCommentsFeature0_1.txt'),
('public/snippets/comments.AverageCommentsFeature0_2.txt'),
('public/snippets/comments.AverageCommentsFeature1_1.txt'),
('public/snippets/comments.AverageCommentsFeature1_2.txt'),
('public/snippets/comments.AverageCommentsFeature2_1.txt'),
('public/snippets/comments.AverageCommentsFeature2_2.txt'),
('public/snippets/comments.TotalCommentsFeature0_1.txt'),
('public/snippets/comments.TotalCommentsFeature0_2.txt'),
('public/snippets/comments.TotalCommentsFeature1_1.txt'),
('public/snippets/comments.TotalCommentsFeature1_2.txt'),
('public/snippets/comments.TotalCommentsFeature2_1.txt'),
('public/snippets/comments.TotalCommentsFeature2_2.txt'),
('public/snippets/comments.TotalExceptionCommentsFeature0_1.txt'),
('public/snippets/comments.TotalExceptionCommentsFeature0_2.txt'),
('public/snippets/comments.TotalExceptionCommentsFeature1_1.txt'),
('public/snippets/comments.TotalExceptionCommentsFeature1_2.txt'),
('public/snippets/comments.TotalExceptionCommentsFeature2_1.txt'),
('public/snippets/comments.TotalExceptionCommentsFeature2_2.txt'),
('public/snippets/entropy.TotalByteEntropyFeature0_1.txt'),
('public/snippets/entropy.TotalByteEntropyFeature0_2.txt'),
('public/snippets/entropy.TotalByteEntropyFeature1_1.txt'),
('public/snippets/entropy.TotalByteEntropyFeature1_2.txt'),
('public/snippets/entropy.TotalByteEntropyFeature2_1.txt'),
('public/snippets/entropy.TotalByteEntropyFeature2_2.txt'),
('public/snippets/entropy.TotalTokenEntropyFeature0_1.txt'),
('public/snippets/entropy.TotalTokenEntropyFeature0_2.txt'),
('public/snippets/entropy.TotalTokenEntropyFeature1_1.txt'),
('public/snippets/entropy.TotalTokenEntropyFeature1_2.txt'),
('public/snippets/entropy.TotalTokenEntropyFeature2_1.txt'),
('public/snippets/entropy.TotalTokenEntropyFeature2_2.txt'),
('public/snippets/fields.MaxFieldAccessFeature0_1.txt'),
('public/snippets/fields.MaxFieldAccessFeature0_2.txt'),
('public/snippets/fields.MaxFieldAccessFeature1_1.txt'),
('public/snippets/fields.MaxFieldAccessFeature1_2.txt'),
('public/snippets/fields.TotalFieldAccessFeature0_1.txt'),
('public/snippets/fields.TotalFieldAccessFeature0_2.txt'),
('public/snippets/fields.TotalFieldAccessFeature1_1.txt'),
('public/snippets/fields.TotalFieldAccessFeature1_2.txt'),
('public/snippets/fields.TotalFieldAccessFeature2_1.txt'),
('public/snippets/fields.TotalFieldAccessFeature2_2.txt'),
('public/snippets/halstead.TotalHalsteadDifficultyFeature0_1.txt'),
('public/snippets/halstead.TotalHalsteadDifficultyFeature0_2.txt'),
('public/snippets/halstead.TotalHalsteadDifficultyFeature1_1.txt'),
('public/snippets/halstead.TotalHalsteadDifficultyFeature1_2.txt'),
('public/snippets/halstead.TotalHalsteadDifficultyFeature2_1.txt'),
('public/snippets/halstead.TotalHalsteadDifficultyFeature2_2.txt'),
('public/snippets/HasExceptionsFeature0_1.txt'),
('public/snippets/HasExceptionsFeature0_2.txt'),
('public/snippets/HasExceptionsFeature1_1.txt'),
('public/snippets/HasExceptionsFeature1_2.txt'),
('public/snippets/identifiers.AverageIdentifiersFeature0_1.txt'),
('public/snippets/identifiers.AverageIdentifiersFeature0_2.txt'),
('public/snippets/identifiers.AverageIdentifiersFeature1_1.txt'),
('public/snippets/identifiers.AverageIdentifiersFeature1_2.txt'),
('public/snippets/identifiers.AverageIdentifiersFeature2_1.txt'),
('public/snippets/identifiers.AverageIdentifiersFeature2_2.txt'),
('public/snippets/identifiers.MaxDistinctClassesFeature0_1.txt'),
('public/snippets/identifiers.MaxDistinctClassesFeature0_2.txt'),
('public/snippets/identifiers.MaxDistinctClassesFeature1_1.txt'),
('public/snippets/identifiers.MaxDistinctClassesFeature1_2.txt'),
('public/snippets/identifiers.MaxDistinctMethodsFeature0_1.txt'),
('public/snippets/identifiers.MaxDistinctMethodsFeature0_2.txt'),
('public/snippets/identifiers.MaxDistinctMethodsFeature1_1.txt'),
('public/snippets/identifiers.MaxDistinctMethodsFeature1_2.txt'),
('public/snippets/identifiers.MaxDistinctMethodsFeature2_1.txt'),
('public/snippets/identifiers.MaxDistinctMethodsFeature2_2.txt'),
('public/snippets/identifiers.MaxIdentifiersFeature0_1.txt'),
('public/snippets/identifiers.MaxIdentifiersFeature0_2.txt'),
('public/snippets/identifiers.MaxIdentifiersFeature1_1.txt'),
('public/snippets/identifiers.MaxIdentifiersFeature1_2.txt'),
('public/snippets/identifiers.MaxIdentifiersFeature2_1.txt'),
('public/snippets/identifiers.MaxIdentifiersFeature2_2.txt'),
('public/snippets/identifiers.MaxUnusedIdentifiersFeature0_1.txt'),
('public/snippets/identifiers.MaxUnusedIdentifiersFeature0_2.txt'),
('public/snippets/identifiers.MaxUnusedIdentifiersFeature1_1.txt'),
('public/snippets/identifiers.MaxUnusedIdentifiersFeature1_2.txt'),
('public/snippets/identifiers.TotalDistinctClassesFeature0_1.txt'),
('public/snippets/identifiers.TotalDistinctClassesFeature0_2.txt'),
('public/snippets/identifiers.TotalDistinctClassesFeature1_1.txt'),
('public/snippets/identifiers.TotalDistinctClassesFeature1_2.txt'),
('public/snippets/identifiers.TotalDistinctClassesFeature2_1.txt'),
('public/snippets/identifiers.TotalDistinctClassesFeature2_2.txt'),
('public/snippets/identifiers.TotalIdentifiersFeature0_1.txt'),
('public/snippets/identifiers.TotalIdentifiersFeature0_2.txt'),
('public/snippets/identifiers.TotalIdentifiersFeature1_1.txt'),
('public/snippets/identifiers.TotalIdentifiersFeature1_2.txt'),
('public/snippets/identifiers.TotalIdentifiersFeature2_1.txt'),
('public/snippets/identifiers.TotalIdentifiersFeature2_2.txt'),
('public/snippets/identifiers.TotalMethodRatioFeature0_1.txt'),
('public/snippets/identifiers.TotalMethodRatioFeature0_2.txt'),
('public/snippets/identifiers.TotalMethodRatioFeature1_1.txt'),
('public/snippets/identifiers.TotalMethodRatioFeature1_2.txt'),
('public/snippets/identifiers.TotalMethodRatioFeature2_1.txt'),
('public/snippets/identifiers.TotalMethodRatioFeature2_2.txt'),
('public/snippets/keywords.AverageKeywordsFeature0_1.txt'),
('public/snippets/keywords.AverageKeywordsFeature0_2.txt'),
('public/snippets/keywords.AverageKeywordsFeature1_1.txt'),
('public/snippets/keywords.AverageKeywordsFeature1_2.txt'),
('public/snippets/keywords.AverageKeywordsFeature2_1.txt'),
('public/snippets/keywords.AverageKeywordsFeature2_2.txt'),
('public/snippets/lines.AverageBlankLinesFeature0_1.txt'),
('public/snippets/lines.AverageBlankLinesFeature0_2.txt'),
('public/snippets/lines.AverageBlankLinesFeature1_1.txt'),
('public/snippets/lines.AverageBlankLinesFeature1_2.txt'),
('public/snippets/lines.AverageBlankLinesFeature2_1.txt'),
('public/snippets/lines.AverageBlankLinesFeature2_2.txt'),
('public/snippets/lines.AverageLineLengthFeature0_1.txt'),
('public/snippets/lines.AverageLineLengthFeature0_2.txt'),
('public/snippets/lines.AverageLineLengthFeature1_1.txt'),
('public/snippets/lines.AverageLineLengthFeature1_2.txt'),
('public/snippets/lines.AverageLineLengthFeature2_1.txt'),
('public/snippets/lines.AverageLineLengthFeature2_2.txt'),
('public/snippets/lines.AverageSpacesFeature0_1.txt'),
('public/snippets/lines.AverageSpacesFeature0_2.txt'),
('public/snippets/lines.AverageSpacesFeature1_1.txt'),
('public/snippets/lines.AverageSpacesFeature1_2.txt'),
('public/snippets/lines.AverageSpacesFeature2_1.txt'),
('public/snippets/lines.AverageSpacesFeature2_2.txt'),
('public/snippets/lines.MaxIndentationsFeature0_1.txt'),
('public/snippets/lines.MaxIndentationsFeature0_2.txt'),
('public/snippets/lines.MaxIndentationsFeature1_1.txt'),
('public/snippets/lines.MaxIndentationsFeature1_2.txt'),
('public/snippets/lines.MaxIndentationsFeature2_1.txt'),
('public/snippets/lines.MaxIndentationsFeature2_2.txt'),
('public/snippets/lines.MaxSpacesFeature0_1.txt'),
('public/snippets/lines.MaxSpacesFeature0_2.txt'),
('public/snippets/lines.MaxSpacesFeature1_1.txt'),
('public/snippets/lines.MaxSpacesFeature1_2.txt'),
('public/snippets/lines.MaxSpacesFeature2_1.txt'),
('public/snippets/lines.MaxSpacesFeature2_2.txt'),
('public/snippets/lines.TotalBlankLinesFeature0_1.txt'),
('public/snippets/lines.TotalBlankLinesFeature0_2.txt'),
('public/snippets/lines.TotalBlankLinesFeature1_1.txt'),
('public/snippets/lines.TotalBlankLinesFeature1_2.txt'),
('public/snippets/lines.TotalBlankLinesFeature2_1.txt'),
('public/snippets/lines.TotalBlankLinesFeature2_2.txt'),
('public/snippets/lines.TotalTestLengthFeature0_1.txt'),
('public/snippets/lines.TotalTestLengthFeature0_2.txt'),
('public/snippets/lines.TotalTestLengthFeature1_1.txt'),
('public/snippets/lines.TotalTestLengthFeature1_2.txt'),
('public/snippets/lines.TotalTestLengthFeature2_1.txt'),
('public/snippets/lines.TotalTestLengthFeature2_2.txt'),
('public/snippets/literals.MaxFloatsFeature0_1.txt'),
('public/snippets/literals.MaxFloatsFeature0_2.txt'),
('public/snippets/literals.MaxFloatsFeature1_1.txt'),
('public/snippets/literals.MaxFloatsFeature1_2.txt'),
('public/snippets/literals.MaxFloatsFeature2_1.txt'),
('public/snippets/literals.MaxFloatsFeature2_2.txt'),
('public/snippets/literals.MaxNullsFeature0_1.txt'),
('public/snippets/literals.MaxNullsFeature0_2.txt'),
('public/snippets/literals.MaxNullsFeature1_1.txt'),
('public/snippets/literals.MaxNullsFeature1_2.txt'),
('public/snippets/literals.MaxStringsFeature0_1.txt'),
('public/snippets/literals.MaxStringsFeature0_2.txt'),
('public/snippets/literals.MaxStringsFeature1_1.txt'),
('public/snippets/literals.MaxStringsFeature1_2.txt'),
('public/snippets/literals.MaxStringsFeature2_1.txt'),
('public/snippets/literals.MaxStringsFeature2_2.txt'),
('public/snippets/literals.TotalBooleansFeature0_1.txt'),
('public/snippets/literals.TotalBooleansFeature0_2.txt'),
('public/snippets/literals.TotalBooleansFeature1_1.txt'),
('public/snippets/literals.TotalBooleansFeature1_2.txt'),
('public/snippets/literals.TotalBooleansFeature2_1.txt'),
('public/snippets/literals.TotalBooleansFeature2_2.txt'),
('public/snippets/literals.TotalCharactersFeature0_1.txt'),
('public/snippets/literals.TotalCharactersFeature0_2.txt'),
('public/snippets/literals.TotalCharactersFeature1_1.txt'),
('public/snippets/literals.TotalCharactersFeature1_2.txt'),
('public/snippets/literals.TotalCharactersFeature2_1.txt'),
('public/snippets/literals.TotalCharactersFeature2_2.txt'),
('public/snippets/literals.TotalFloatsFeature0_1.txt'),
('public/snippets/literals.TotalFloatsFeature0_2.txt'),
('public/snippets/literals.TotalFloatsFeature1_1.txt'),
('public/snippets/literals.TotalFloatsFeature1_2.txt'),
('public/snippets/literals.TotalFloatsFeature2_1.txt'),
('public/snippets/literals.TotalFloatsFeature2_2.txt'),
('public/snippets/literals.TotalNullsFeature0_1.txt'),
('public/snippets/literals.TotalNullsFeature0_2.txt'),
('public/snippets/literals.TotalNullsFeature1_1.txt'),
('public/snippets/literals.TotalNullsFeature1_2.txt'),
('public/snippets/literals.TotalNullsFeature2_1.txt'),
('public/snippets/literals.TotalNullsFeature2_2.txt'),
('public/snippets/literals.TotalNumbersFeature0_1.txt'),
('public/snippets/literals.TotalNumbersFeature0_2.txt'),
('public/snippets/literals.TotalNumbersFeature1_1.txt'),
('public/snippets/literals.TotalNumbersFeature1_2.txt'),
('public/snippets/literals.TotalNumbersFeature2_1.txt'),
('public/snippets/literals.TotalNumbersFeature2_2.txt'),
('public/snippets/literals.TotalStringsLengthFeature0_1.txt'),
('public/snippets/literals.TotalStringsLengthFeature0_2.txt'),
('public/snippets/literals.TotalStringsLengthFeature1_1.txt'),
('public/snippets/literals.TotalStringsLengthFeature1_2.txt'),
('public/snippets/literals.TotalStringsLengthFeature2_1.txt'),
('public/snippets/literals.TotalStringsLengthFeature2_2.txt'),
('public/snippets/MaxCastsFeature0_1.txt'),
('public/snippets/MaxCastsFeature0_2.txt'),
('public/snippets/MaxCastsFeature1_1.txt'),
('public/snippets/MaxCastsFeature1_2.txt'),
('public/snippets/stringscore.TotalStringScoreFeature0_1.txt'),
('public/snippets/stringscore.TotalStringScoreFeature0_2.txt'),
('public/snippets/stringscore.TotalStringScoreFeature1_1.txt'),
('public/snippets/stringscore.TotalStringScoreFeature1_2.txt'),
('public/snippets/stringscore.TotalStringScoreFeature2_1.txt'),
('public/snippets/stringscore.TotalStringScoreFeature2_2.txt'),
('public/snippets/TotalCastsFeature0_1.txt'),
('public/snippets/TotalCastsFeature0_2.txt'),
('public/snippets/TotalCastsFeature1_1.txt'),
('public/snippets/TotalCastsFeature1_2.txt'),
('public/snippets/TotalCastsFeature2_1.txt'),
('public/snippets/TotalCastsFeature2_2.txt'),
('public/snippets/TotalIfsFeature0_1.txt'),
('public/snippets/TotalIfsFeature0_2.txt'),
('public/snippets/TotalIfsFeature1_1.txt'),
('public/snippets/TotalIfsFeature1_2.txt'),
('public/snippets/TotalIfsFeature2_1.txt'),
('public/snippets/TotalIfsFeature2_2.txt'),
('public/snippets/TotalLoopsFeature0_1.txt'),
('public/snippets/TotalLoopsFeature0_2.txt'),
('public/snippets/TotalLoopsFeature1_1.txt'),
('public/snippets/TotalLoopsFeature1_2.txt'),
('public/snippets/TotalLoopsFeature2_1.txt'),
('public/snippets/TotalLoopsFeature2_2.txt'),
('public/snippets/types.TotalTypesFeature0_1.txt'),
('public/snippets/types.TotalTypesFeature0_2.txt'),
('public/snippets/types.TotalTypesFeature1_1.txt'),
('public/snippets/types.TotalTypesFeature1_2.txt'),
('public/snippets/types.TotalTypesFeature2_1.txt'),
('public/snippets/types.TotalTypesFeature2_2.txt');

-- END

